### ISSUE TITLE
机枪池增加lp 挖矿

### ISSUE THREAD

**Issue by jin10086** [yfii/dfi#59]
首页vault需要支持两个区切换

进入lp区，需要先弹提示，

提示内容大概是: lp挖矿是有损的（这个需要文案提供）

用户确认后才可以进入

入金方式支持3种
1. lp直接如今
2. 两个代币种的两个单独入金

可能需要换一个图 说明系统是如何运作的

比如 eth/usdt的

用户存 usdt->自动帮忙换成eth/usdt的lp -> uniswap 质押挖矿 -> uni ->换成 eth/usdt lp继续复利挖矿

**Comment by jin10086** [comment]
比如 eth/usdt挖矿的

入金可以选择3个中的随意一个  eth、usdt、eth-usdt lp
出金也是

**Comment by jin10086** [comment]
## 入金

4种

1. token   -> 方法为 deposit 、depositAll
2. token0   -> 方法为 depositToken0、depositToken0All
3. token1 -> 方法为 depositToken1、depositToken1All
4. eth -> 方法为 depositETH

## 出金

1. token   -> 方法为 withdraw 、withdrawAll
2. token0   -> 方法为 withdrawToken0、withdrawToken0All
3. token1 -> 方法为 withdrawToken1、withdrawToken1All
4. eth -> 方法为 withdrawETH   withdrawETHAll

**Comment by qqonline** [comment]
假设入金 USDT，这时候是帮用户换一部分eth，然后合成lp吗？

还是A用户入金USDT，等B用户入金ETH之后，撮合合成lp呢？

这两种方式的风险是不一样的，撮合合成的风险会小很多（A和B用户都币本位的前提下）。

当然撮合的方式，资金利用率会下降（需要等有撮合的匹配）。

看YFV的宣传图，他们也是打算使用撮合合成的方式。
